export const GAME = {
  title: "Lumora",
  mascot: "Nuri",
  currency: "Gleams",
  version: "1.2.0",
  saveKey: "lumora.save.v1",
  debugQuery: "debug",
};

export const DIRS = {
  UP: { x: 0, y: -1, name: "up" },
  DOWN: { x: 0, y: 1, name: "down" },
  LEFT: { x: -1, y: 0, name: "left" },
  RIGHT: { x: 1, y: 0, name: "right" },
};

export const DIR_LIST = [DIRS.UP, DIRS.DOWN, DIRS.LEFT, DIRS.RIGHT];

export const TILE = {
  VOID: 0,
  SHARD: 1,
  PILLAR: 2,
  RIFT: 3,
  ANCHOR: 4,
  WELL: 5,
  SEAL: 6,
  FOLD: 7,
  VANE: 8,
  HEART: 9,
  FRACTURE: 10,
  MIRROR: 11,
  ONEWAY: 12,
};

/** Primary goal is always restoring every floor tile. Variants add constraints. */
export const OBJECTIVE = {
  RESTORE: "restore",
  SAFE: "safe",
  WELLS: "wells",
  SEQUENCE: "sequence",
  FOLD: "fold",
};

export const STATES = {
  BOOT: "BOOT",
  LOADING: "LOADING",
  INTRO: "INTRO",
  MAIN_MENU: "MAIN_MENU",
  WORLD_SELECT: "WORLD_SELECT",
  LEVEL_SELECT: "LEVEL_SELECT",
  WORLD_INTRO: "WORLD_INTRO",
  PLAYING: "PLAYING",
  PAUSED: "PAUSED",
  LEVEL_COMPLETE: "LEVEL_COMPLETE",
  REWARD: "REWARD",
  COLLECTION: "COLLECTION",
  SETTINGS: "SETTINGS",
  DAILY_CHALLENGE: "DAILY_CHALLENGE",
  ACHIEVEMENTS: "ACHIEVEMENTS",
};

export const QUALITY = {
  LOW: "low",
  MEDIUM: "medium",
  HIGH: "high",
};

export const WORLDS = [
  { id: "emberwake", name: "Emberwake", tagline: "Warm stone learning to glow", levels: 10, intro: "restore", hue: "#ff9a4a" },
  { id: "tidecrest", name: "Tidecrest", tagline: "Cool glass and drinking wells", levels: 10, intro: "well", hue: "#48d8d0" },
  { id: "duskveil", name: "Duskveil", tagline: "Seals sleep until called", levels: 10, intro: "seal", hue: "#c890f0" },
  { id: "canopy", name: "Canopy", tagline: "Drift vanes turn the glide", levels: 10, intro: "vane", hue: "#a8e050" },
  { id: "starloom", name: "Starloom", tagline: "Foldgates stitch the dark", levels: 10, intro: "fold", hue: "#88a8ff" },
  { id: "cinderfall", name: "Cinderfall", tagline: "Ash plates crumble behind you", levels: 10, intro: "fracture", hue: "#ff7040" },
  { id: "mirrorfen", name: "Mirrorfen", tagline: "Silver faces reverse the wake", levels: 10, intro: "mirror", hue: "#9ee0d0" },
  { id: "zephyrrow", name: "Zephyrrow", tagline: "Winds only blow one way", levels: 10, intro: "oneway", hue: "#7ec8ff" },
  { id: "brasslock", name: "Brasslock", tagline: "Golden rings bar the path", levels: 10, intro: "seal", hue: "#e0b050" },
  { id: "hollowmere", name: "Hollowmere", tagline: "Rifts tear the still water", levels: 10, intro: "rift", hue: "#c07090" },
  { id: "prismarch", name: "Prismarch", tagline: "Beacons demand a true order", levels: 10, intro: "sequence", hue: "#f0a0ff" },
  { id: "auroraloom", name: "Auroraloom", tagline: "A hidden heart in the folds", levels: 10, intro: "heart", hue: "#80e0ff" },
  { id: "rootspire", name: "Rootspire", tagline: "Dense crystal forests", levels: 10, intro: "pillar", hue: "#6ecf7a" },
  { id: "stormglass", name: "Stormglass", tagline: "One-way gales over rifts", levels: 10, intro: "storm", hue: "#6aa8ff" },
  { id: "duskforge", name: "Duskforge", tagline: "Ash plates and tearing rifts", levels: 10, intro: "forge", hue: "#ff6080" },
];

/** Short visual briefings shown the first time a world is entered. */
export const WORLD_INTROS = {
  emberwake: { title: "The Void Rim", line: "Glide until the drop. Light every plate.", art: "restore" },
  tidecrest: { title: "Drinking Wells", line: "Rest on a well to charge it.", art: "well" },
  duskveil: { title: "Sleeping Seals", line: "Wake the blossom. The ring opens.", art: "seal" },
  canopy: { title: "Drift Vanes", line: "Spinning tiles turn your glide.", art: "vane" },
  starloom: { title: "Foldgates", line: "Paired gates stitch you across the dark.", art: "fold" },
  cinderfall: { title: "Ash Plates", line: "Leave a cracked tile and it falls away.", art: "fracture" },
  mirrorfen: { title: "Silver Faces", line: "Mirrors snap your wake the other way.", art: "mirror" },
  zephyrrow: { title: "One Wind", line: "Arrows only let you pass with the gale.", art: "oneway" },
  hollowmere: { title: "Stillwater Rifts", line: "Dark tears unravel the run. Steer clear.", art: "rift" },
  prismarch: { title: "True Order", line: "Wake numbered beacons in sequence.", art: "sequence" },
  brasslock: { title: "Golden Rings", line: "Each lock needs its own blossom.", art: "seal" },
  auroraloom: { title: "Hidden Heart", line: "Find the heart, then ride the folds.", art: "heart" },
  rootspire: { title: "Crystal Forest", line: "Tall crystals stop Nuri. Thread the grove.", art: "pillar" },
  stormglass: { title: "Gale & Tear", line: "Ride the arrows. Never kiss a rift.", art: "storm" },
  duskforge: { title: "Ash & Tear", line: "Plates crumble. Rifts punish a misstep.", art: "forge" },
};

/** World base themes — per-level accents are derived in palette.js */
export const PALETTES = {
  emberwake: {
    skyTop: "#1c1218",
    skyBot: "#3d241f",
    fog: "#c4784a",
    floor: "#4a3030",
    floorLit: "#ffb86a",
    sideL: "#3a2426",
    sideR: "#2a181a",
    sideLLit: "#d47840",
    sideRLit: "#a85828",
    pillar: "#2a1c1e",
    accent: "#ff9a4a",
    accentDeep: "#d45a28",
    ink: "#fff4ea",
    mute: "#d4b8a8",
    rim: "#ffd0a0",
  },
  tidecrest: {
    skyTop: "#0c1c28",
    skyBot: "#163848",
    fog: "#4ec8c8",
    floor: "#1e3c48",
    floorLit: "#7ef0e0",
    sideL: "#163440",
    sideR: "#0e2430",
    sideLLit: "#38b8b0",
    sideRLit: "#248888",
    pillar: "#102830",
    accent: "#48d8d0",
    accentDeep: "#1e8888",
    ink: "#e8fffc",
    mute: "#a0c8c8",
    rim: "#b8fff4",
  },
  duskveil: {
    skyTop: "#14101f",
    skyBot: "#2c1c48",
    fog: "#b070e0",
    floor: "#322448",
    floorLit: "#e0b0ff",
    sideL: "#281838",
    sideR: "#1c102c",
    sideLLit: "#a060d0",
    sideRLit: "#7030a0",
    pillar: "#1c142c",
    accent: "#c890f0",
    accentDeep: "#8040c0",
    ink: "#f8f0ff",
    mute: "#c0b0d8",
    rim: "#f0d0ff",
  },
  canopy: {
    skyTop: "#101c14",
    skyBot: "#243c28",
    fog: "#78c060",
    floor: "#243c2c",
    floorLit: "#c8f070",
    sideL: "#1c3024",
    sideR: "#14241a",
    sideLLit: "#78b048",
    sideRLit: "#508030",
    pillar: "#14241a",
    accent: "#a8e050",
    accentDeep: "#589828",
    ink: "#f4ffe8",
    mute: "#b0c8a8",
    rim: "#e0ffb0",
  },
  starloom: {
    skyTop: "#0a0e20",
    skyBot: "#182448",
    fog: "#7090f0",
    floor: "#1c2848",
    floorLit: "#b8d0ff",
    sideL: "#141e38",
    sideR: "#0c1428",
    sideLLit: "#6080e0",
    sideRLit: "#4060b0",
    pillar: "#0c1428",
    accent: "#88a8ff",
    accentDeep: "#4060d0",
    ink: "#f0f4ff",
    mute: "#a8b8d8",
    rim: "#d0e0ff",
  },
  daily: {
    skyTop: "#1c1018",
    skyBot: "#382030",
    fog: "#f080a8",
    floor: "#382030",
    floorLit: "#ffb0c8",
    sideL: "#2c1824",
    sideR: "#1e1018",
    sideLLit: "#d06088",
    sideRLit: "#a03860",
    pillar: "#1e1018",
    accent: "#f090b0",
    accentDeep: "#c04070",
    ink: "#fff0f6",
    mute: "#d8b0c0",
    rim: "#ffd0e0",
  },
  cinderfall: {
    skyTop: "#1a0e0c",
    skyBot: "#3c1c14",
    fog: "#ff7040",
    floor: "#3a221c",
    floorLit: "#ff9a60",
    sideL: "#2c1814",
    sideR: "#1e100e",
    sideLLit: "#d05830",
    sideRLit: "#a03820",
    pillar: "#1a100e",
    accent: "#ff7040",
    accentDeep: "#c03818",
    ink: "#fff0e8",
    mute: "#d4b0a0",
    rim: "#ffc8a0",
  },
  mirrorfen: {
    skyTop: "#0c1c1c",
    skyBot: "#1a3838",
    fog: "#9ee0d0",
    floor: "#1c3c3c",
    floorLit: "#c8fff0",
    sideL: "#163030",
    sideR: "#0e2222",
    sideLLit: "#58c0b0",
    sideRLit: "#388888",
    pillar: "#102424",
    accent: "#9ee0d0",
    accentDeep: "#2a8880",
    ink: "#f0fffc",
    mute: "#a8d0c8",
    rim: "#d8fff4",
  },
  zephyrrow: {
    skyTop: "#0c1828",
    skyBot: "#1c3c58",
    fog: "#7ec8ff",
    floor: "#1c3850",
    floorLit: "#a8e0ff",
    sideL: "#163044",
    sideR: "#0e2030",
    sideLLit: "#4aa0e0",
    sideRLit: "#2878b0",
    pillar: "#102030",
    accent: "#7ec8ff",
    accentDeep: "#2a70b8",
    ink: "#eef8ff",
    mute: "#a8c8e0",
    rim: "#c8ecff",
  },
  brasslock: {
    skyTop: "#1c140c",
    skyBot: "#3c2c14",
    fog: "#e0b050",
    floor: "#3c3020",
    floorLit: "#f0d070",
    sideL: "#302818",
    sideR: "#20180e",
    sideLLit: "#c09038",
    sideRLit: "#906828",
    pillar: "#1c140c",
    accent: "#e0b050",
    accentDeep: "#a07020",
    ink: "#fff8e8",
    mute: "#d4c4a0",
    rim: "#ffe8a8",
  },
  hollowmere: {
    skyTop: "#180c14",
    skyBot: "#381828",
    fog: "#c07090",
    floor: "#3c2030",
    floorLit: "#f0a0b8",
    sideL: "#301824",
    sideR: "#201018",
    sideLLit: "#b05070",
    sideRLit: "#803048",
    pillar: "#1c1014",
    accent: "#c07090",
    accentDeep: "#903050",
    ink: "#fff0f4",
    mute: "#d0b0bc",
    rim: "#ffd0dc",
  },
  prismarch: {
    skyTop: "#180c20",
    skyBot: "#381848",
    fog: "#f0a0ff",
    floor: "#3c2448",
    floorLit: "#f8c8ff",
    sideL: "#301838",
    sideR: "#201028",
    sideLLit: "#c060e0",
    sideRLit: "#9030b0",
    pillar: "#1c1028",
    accent: "#f0a0ff",
    accentDeep: "#a040c8",
    ink: "#fcf0ff",
    mute: "#d8b8e8",
    rim: "#ffd8ff",
  },
  auroraloom: {
    skyTop: "#081820",
    skyBot: "#143848",
    fog: "#80e0ff",
    floor: "#1c3848",
    floorLit: "#b8f4ff",
    sideL: "#143040",
    sideR: "#0c202c",
    sideLLit: "#40b0d0",
    sideRLit: "#2888a8",
    pillar: "#0c1c28",
    accent: "#80e0ff",
    accentDeep: "#2898b8",
    ink: "#f0fcff",
    mute: "#a8d0dc",
    rim: "#d0f8ff",
  },
  rootspire: {
    skyTop: "#0c1a12",
    skyBot: "#1c3824",
    fog: "#6ecf7a",
    floor: "#244830",
    floorLit: "#b8f090",
    sideL: "#1c3828",
    sideR: "#12241a",
    sideLLit: "#58a848",
    sideRLit: "#387830",
    pillar: "#102418",
    accent: "#6ecf7a",
    accentDeep: "#2e8a40",
    ink: "#f2ffe8",
    mute: "#b0d0b0",
    rim: "#d8ffc0",
  },
  stormglass: {
    skyTop: "#08141c",
    skyBot: "#183048",
    fog: "#6aa8ff",
    floor: "#1c3048",
    floorLit: "#a0c8ff",
    sideL: "#142438",
    sideR: "#0c1828",
    sideLLit: "#4078d0",
    sideRLit: "#2858a0",
    pillar: "#0c1828",
    accent: "#6aa8ff",
    accentDeep: "#2860c0",
    ink: "#eef4ff",
    mute: "#a8bce0",
    rim: "#c8dcff",
  },
  duskforge: {
    skyTop: "#18080e",
    skyBot: "#3c1424",
    fog: "#ff6080",
    floor: "#3c1c28",
    floorLit: "#ff90a8",
    sideL: "#30141c",
    sideR: "#200e14",
    sideLLit: "#d04060",
    sideRLit: "#a02840",
    pillar: "#180c12",
    accent: "#ff6080",
    accentDeep: "#c02848",
    ink: "#fff0f4",
    mute: "#d8b0b8",
    rim: "#ffc0d0",
  },
};

export const COSMETICS = [
  { id: "nuri-dawn", type: "body", name: "Dawnpelt", cost: 0, unlock: "start" },
  { id: "nuri-tide", type: "body", name: "Tidecoat", cost: 40 },
  { id: "nuri-dusk", type: "body", name: "Dusksilk", cost: 60 },
  { id: "nuri-leaf", type: "body", name: "Leafglow", cost: 80 },
  { id: "nuri-star", type: "body", name: "Stardown", cost: 100 },
  { id: "wake-ribbon", type: "wake", name: "Soft Ribbon", cost: 0, unlock: "start" },
  { id: "wake-petals", type: "wake", name: "Petal Drift", cost: 50 },
  { id: "wake-sparks", type: "wake", name: "Spark Beads", cost: 70 },
  { id: "mote-orbs", type: "mote", name: "Tiny Orbs", cost: 0, unlock: "start" },
  { id: "mote-rings", type: "mote", name: "Halo Rings", cost: 45 },
  { id: "burst-bloom", type: "burst", name: "Quiet Bloom", cost: 0, unlock: "start" },
  { id: "burst-constellation", type: "burst", name: "Constellation", cost: 90 },
  { id: "sky-still", type: "sky", name: "Still Dusk", cost: 0, unlock: "start" },
  { id: "sky-aurora", type: "sky", name: "Lattice Aurora", cost: 75 },
];

export const ACHIEVEMENTS = [
  { id: "first-wake", name: "First Wake", desc: "Restore your first lattice.", icon: "wake" },
  { id: "ten-lattices", name: "Ten Lattices", desc: "Restore 10 lattices.", icon: "ten" },
  { id: "fifty-lattices", name: "Fifty Lattices", desc: "Restore 50 lattices.", icon: "fifty" },
  ...WORLDS.map((w) => ({
    id: `world-${w.id}`,
    name: `${w.name} Keeper`,
    desc: `Complete every lattice in ${w.name}.`,
    icon: w.id,
  })),
  { id: "efficient", name: "Quiet Path", desc: "Finish within the quiet-glide hint.", icon: "quiet" },
  { id: "daily", name: "Day Weaver", desc: "Complete a Dayweave lattice.", icon: "daily" },
  { id: "collector", name: "Wardrobe", desc: "Unlock 6 cosmetics.", icon: "wardrobe" },
  { id: "well-tender", name: "Well Tender", desc: "Charge a well for the first time.", icon: "well" },
  { id: "fold-step", name: "Fold Step", desc: "Travel through a foldgate.", icon: "fold" },
];

export const QUALITY_PRESETS = {
  low: { motes: 16, wake: 8, burst: 20, stars: 10 },
  medium: { motes: 32, wake: 16, burst: 40, stars: 20 },
  high: { motes: 52, wake: 26, burst: 64, stars: 32 },
};
